import type { Puppy, Breeder } from "./types"

export const mockBreeders: Breeder[] = [
  {
    id: "1",
    userId: "user1",
    businessName: "Golden Paws Kennel",
    verified: true,
    rating: 4.8,
    totalReviews: 127,
    location: "Austin, TX",
    phone: "+1 (555) 123-4567",
    email: "contact@goldenpaws.com",
    description: "Professional breeder specializing in Golden Retrievers and Labradors",
    avatar: "/professional-dog-breeder.jpg",
  },
  {
    id: "2",
    userId: "user2",
    businessName: "Happy Tails Breeding",
    verified: true,
    rating: 4.9,
    totalReviews: 89,
    location: "Portland, OR",
    phone: "+1 (555) 234-5678",
    email: "info@happytails.com",
    description: "Family-owned breeding program focused on healthy, happy puppies",
    avatar: "/family-dog-breeder.jpg",
  },
  {
    id: "3",
    userId: "user3",
    businessName: "Elite Canine Breeders",
    verified: true,
    rating: 4.7,
    totalReviews: 156,
    location: "Denver, CO",
    phone: "+1 (555) 345-6789",
    email: "hello@elitecanine.com",
    description: "Award-winning breeders of champion bloodline dogs",
    avatar: "/elite-dog-breeder.jpg",
  },
]

export const mockPuppies: Puppy[] = [
  {
    id: "1",
    name: "Max",
    breed: "Golden Retriever",
    age: 8,
    price: 1500,
    gender: "male",
    location: "Austin, TX",
    description: "Adorable Golden Retriever puppy with a playful personality. Great with kids and other pets.",
    images: ["/golden-retriever-puppy.png", "/golden-retriever-puppy-playing.jpg", "/golden-retriever-puppy-portrait.jpg"],
    breederId: "1",
    breeder: mockBreeders[0],
    healthInfo: {
      vaccinated: true,
      dewormed: true,
      vetChecked: true,
      healthCertificate: true,
    },
    availability: "available",
    size: "large",
    color: "Golden",
    temperament: ["Friendly", "Energetic", "Loyal"],
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "2",
    name: "Luna",
    breed: "French Bulldog",
    age: 10,
    price: 2500,
    gender: "female",
    location: "Portland, OR",
    description: "Sweet French Bulldog with a calm temperament. Perfect for apartment living.",
    images: ["/french-bulldog-puppy.png", "/french-bulldog-puppy-sitting.jpg", "/french-bulldog-puppy-cute.jpg"],
    breederId: "2",
    breeder: mockBreeders[1],
    healthInfo: {
      vaccinated: true,
      dewormed: true,
      vetChecked: true,
      healthCertificate: true,
    },
    availability: "available",
    size: "small",
    color: "Fawn",
    temperament: ["Calm", "Affectionate", "Playful"],
    createdAt: new Date("2025-01-18"),
  },
  {
    id: "3",
    name: "Rocky",
    breed: "German Shepherd",
    age: 12,
    price: 1800,
    gender: "male",
    location: "Denver, CO",
    description: "Intelligent German Shepherd puppy from champion bloodlines. Excellent for training.",
    images: ["/german-shepherd-puppy.png", "/german-shepherd-puppy-alert.jpg", "/german-shepherd-puppy-running.jpg"],
    breederId: "3",
    breeder: mockBreeders[2],
    healthInfo: {
      vaccinated: true,
      dewormed: true,
      vetChecked: true,
      healthCertificate: true,
    },
    availability: "available",
    size: "large",
    color: "Black & Tan",
    temperament: ["Intelligent", "Protective", "Loyal"],
    createdAt: new Date("2025-01-20"),
  },
  {
    id: "4",
    name: "Bella",
    breed: "Labrador Retriever",
    age: 9,
    price: 1400,
    gender: "female",
    location: "Austin, TX",
    description: "Friendly Labrador puppy with a gentle nature. Great family companion.",
    images: ["/labrador-puppy.png", "/labrador-puppy-yellow.jpg", "/labrador-puppy-happy.jpg"],
    breederId: "1",
    breeder: mockBreeders[0],
    healthInfo: {
      vaccinated: true,
      dewormed: true,
      vetChecked: true,
      healthCertificate: true,
    },
    availability: "available",
    size: "large",
    color: "Yellow",
    temperament: ["Friendly", "Gentle", "Outgoing"],
    createdAt: new Date("2025-01-22"),
  },
  {
    id: "5",
    name: "Charlie",
    breed: "Pomeranian",
    age: 7,
    price: 1200,
    gender: "male",
    location: "Portland, OR",
    description: "Fluffy Pomeranian with a big personality in a small package.",
    images: ["/pomeranian-puppy.jpg", "/pomeranian-puppy-fluffy.jpg", "/pomeranian-puppy-orange.jpg"],
    breederId: "2",
    breeder: mockBreeders[1],
    healthInfo: {
      vaccinated: true,
      dewormed: true,
      vetChecked: true,
      healthCertificate: true,
    },
    availability: "available",
    size: "small",
    color: "Orange",
    temperament: ["Lively", "Bold", "Friendly"],
    createdAt: new Date("2025-01-25"),
  },
  {
    id: "6",
    name: "Daisy",
    breed: "Beagle",
    age: 11,
    price: 1100,
    gender: "female",
    location: "Denver, CO",
    description: "Curious Beagle puppy with a great nose and friendly disposition.",
    images: ["/beagle-puppy.png", "/beagle-puppy-tricolor.jpg", "/beagle-puppy-cute.jpg"],
    breederId: "3",
    breeder: mockBreeders[2],
    healthInfo: {
      vaccinated: true,
      dewormed: true,
      vetChecked: true,
      healthCertificate: true,
    },
    availability: "available",
    size: "medium",
    color: "Tricolor",
    temperament: ["Curious", "Friendly", "Merry"],
    createdAt: new Date("2025-01-28"),
  },
]

export const popularBreeds = [
  "Golden Retriever",
  "French Bulldog",
  "German Shepherd",
  "Labrador Retriever",
  "Pomeranian",
  "Beagle",
  "Bulldog",
  "Poodle",
  "Rottweiler",
  "Yorkshire Terrier",
]
